# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5da93895ddac3343246af05289882b2b0347e509ea48fbcdd2e73ca0a331c0ae8e84314f422f351681d3a6fffc9efc18640db56f805af5f70226b74bbb4df446

test:
  secret_key_base: 1f9efbe07346dd6f445e239f779fbf06c7422d4dd85ea08271e91af0a97fdb9c793b8c53d076c9c1641b82c1f05b115cd1c465fe0f42c121644bf193a92d883f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
